apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "616460528989046813"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/davidxie/emco
status: {}
