apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kust6603177569334385310
  namespace: default
spec:
  interval: 1m0s
  path: clusters/provider-flux+cluster2/context/6603177569334385310
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: "6603177569334385310"
  timeout: 1m0s
status: {}
